#  ____     ___ |    / _____ _____
# |  __    |    |___/    |     |
# |___| ___|    |    \ __|__   |     gsKit Open Source Project.
# ----------------------------------------------------------------------
# Copyright 2004 - Chris "Neovanglist" Gilbert <Neovanglist@LainOS.org>
# Licenced under Academic Free License version 2.0
# Review gsKit README & LICENSE files for further details.
#
# examples/speed/Makefile - Makefile for "speed" example.
#

EE_BIN  = speed.elf
EE_OBJS = speed.o

include ../../Makefile.pref
include ../Makefile.global
